homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns =[
	path('', views.profile, name='profil'),
	path('profile/', views.profile, name='profile'),
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('photo/', views.photo, name='photo'),
	path('kegiatan/', views.kegiatan, name='kegiatan'),
	path('tambah/', views.tambah, name='tambah'),
	path('pilih/<kegiatan_id>', views.pilih, name='pilih'),
	path('hapus/', views.hapusKegiatan, name='hapus'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
		name = models.CharField(max_length = 100)
		tanggal = models.DateField()
		tempat = models.CharField(max_length = 50)
		jam = models.TimeField()
		kategori = models.CharField(max_length=150)
		pilih = models.BooleanField(default = False)

		def __str__(self):
			return self.name
		

homepage/forms.py
from django import forms

class FormSchedule(forms.Form):
	name = forms.CharField(max_length = 60, widget=forms.TextInput(attrs={'class': 'form-control',
		   'placeholder':'ct : futsal', 'id' : 'nama'}))
	tanggal = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control',
			  'placeholder':'', 'type':'date'}))
	tempat = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class':'form-control',
		      'placeholder': 'ct : rumah hantu'}))
	jam = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control','type':'time'}))
	kategori = forms.CharField(max_length=150,
			widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'ct:tugas rumah'}))

homepage/views.py
from django.shortcuts import render, redirect
from .forms import FormSchedule
from .models import Schedule
from django.views.decorators.http import require_POST

# Create your views here.
def kegiatan(request):
	list_schedule = Schedule.objects.order_by('tanggal')
	form = FormSchedule()
	context = {'list_schedule' : list_schedule, 'form' : form}
	return render(request, 'story3v.html', context)

@require_POST
def tambah(request):
	form = FormSchedule(request.POST)
	if form.is_valid():
		newSchedule = Schedule(name=request.POST['name'], tanggal=request.POST['tanggal'], tempat=request.POST['tempat'],jam=request.POST['jam'],kategori=request.POST['kategori'])
		newSchedule.save()
	return redirect('homepage:kegiatan')

def pilih(request, kegiatan_id):
	kegiatan = Schedule.objects.get(pk= kegiatan_id)
	if kegiatan.pilih == False:
		kegiatan.pilih = True;
	else:
		kegiatan.pilih = False
	kegiatan.save()
	return redirect('homepage:kegiatan')
def hapusKegiatan(request):
	Schedule.objects.filter(pilih__exact = True).delete()

	return redirect('homepage:kegiatan')


def profile(request):
	return render(request, 'story3i.html')
def about(request):
	return render(request, 'story3ii.html')
def contact(request):
	return render(request, 'story3iii.html')
def photo(request):
	return render(request, 'story3iv.html')

homepage/templates/story3i.html
<!DOCTYPE html>
{% load static %}
<html> 
<head> 
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

	<title>Home</title> 
</head> 
<body > 
  	<div>
		<nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3">
  			<a class="navbar-brand" href="#"><img src="{% static 'images/logotitus.jpg' %}" style="width: 100px;height: 40px;"></a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
    			<ul class="navbar-nav">
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:profile' %}">Home <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:about' %}">About <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:contact' %}">Contact <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:photo' %}">Photo <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:kegiatan' %}">kegiatan <span class="sr-only">(current)</span></a>
      				</li>
    			</ul>
  			</div>
		</nav>
	</div>
	<div id="bghome" class="row flex-row">
		<div  class="col-lg-3 col-md-6 col-sm-12 col-xs-12 pl-2 pr-2" style="left: 3%;margin-right: 2%;top: 2%;">
				<img src="{% static 'images/titus.jpg'%}" class="img-fluid">
				<br/>
		</div>
		<div class="col-lg-5 col-md-8 col-sm-12 col-xs-12 pl-4 pr-2" style="top: 2%;">			
			<div style="background-color: rgba(255, 0, 0, 0.17); height: 320px">
				<div class="text-left text-white" style="font-size: 2rem;">Hi Guys, I am</div>
				<p style="color: white; font-size: 1.5rem;">"Titus Dirgantoro P"</p>
				<p style="color: white;">Birth : 26 March 2001</p>
				<p style="color: white;">Home : Bekasi,Kaliabang Tengah</p>
				<p style="color: white;">Email : titusdirgantoro@gmail.com</p>
				<p style="color: white;">No. Telp : 081286263581</p>
				<br/>
			</div>
		</div>

		
	</div>
	
 
</body> 
</html>

homepage/templates/story3ii.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>About</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/story3.css' %}">
</head>
<body>
	<div>
		<img src="{% static 'images/titusabout.png' %}" class="center" id="fotoabout">
		<div class="center1" id="navigation2">
		<ul class="page1">
	  		<li class="page1"><a href="{% url 'homepage:profile' %}"><font color="black" size="6">Home</font></a></li>
	  		<li class="page1"><a href="{% url 'homepage:about' %}"><font size="6"><b>About</b></font></a></li>
	  		<li class="page1"><a href="{% url 'homepage:contact' %}"><font color="black" size="6">Contact</font></a></li>
		</ul>
	</div>


	<div id="border">
		<img src="{% static 'images/titusabout1.jpg' %}" id="fotoabout1">
	</div>


	<div class="sectionqualities">
		<h1 align="center">QUALITIES</h1>
		<hr>
		<p align="center">Persistent, hard work,</p>
		<p align="center">powerful, patient, and</p>
		<p align="center">humble</p>
	</div>
	<div class="sectionhobbies">
		<h1 align="center">HOBBIES</h1>
		<hr>
		<p align="center"><img src="{% static 'images/hobbies.png' %}" class="hobbies"></p>
	</div>
	<div  class="sectionskill">
		<h1 align="center">SKILL</h1>
            <hr><br>
            <ul>
                <li>HTML <br>
                    <progress min="0" max="100" value="70"></progress>
                </li><br>
                <li>CSS <br>
                    <progress min="0" max="100" value="50"></progress>
                </li><br>
                <li>Python <br>
                    <progress min="0" max="100" value="35"></progress>
                </li><br>
                <li>Java <br>
                	<progress min="0" max="100" value="45"></progress>     	
                </li>
            </ul>
	</div>
	</div>


	<div>
		<img src="{% static 'images/bgabout1.png' %}" class="center" id="bgabout">
		<div>
		<img src="{% static 'images/bgabout.png' %}" class="center" id="bgabout1">
	</div>
	<div class="center" id="kepanitiaan">
	 <h1 align="center" class="kepanitiaan"> KEPANITIAAN & ORGANISASI </h1>
		<hr>
	</div>
	
	<div>
		<img src="{% static 'images/depor.jpg' %}" class="fotokepanitiaan" id="depor">
		<hr class="center" id="hrdepor">
	</div>
	<div class="center" id="tulisandepor">
		<h2 class="kepanitiaan2"> BEM Fasilkom UI </h2>
	</div>

	
	<div>
		<img src="{% static 'images/kir.jpg' %}" class="fotokepanitiaan" id="kir">
		<hr class="center" id="hrkir">
	</div>
	<div class="center" id="tulisankir">
		<h2 class="kepanitiaan2"> Kelompok Ilmiah Remaja </h2>
	</div>

	
	<div>
		<img src="{% static 'images/runtime.jpg' %}" class="fotokepanitiaan" id="runtime">
	</div>
	<div class="center" id="tulisanRE">
		<h2 class="kepanitiaan2"> Runtime Error CSUI </h2>
	</div>
	</div>
	
		

	
	<div>
		<img src="{% static 'images/bgabout1.jpg' %}" class="center" id="bgabout2">
		<div>
		<img src="{% static 'images/education.png' %}" class="center" id="bgabout2">
	</div>
	<div>
		<p class="center" id="logo"><img src="{% static 'images/sd.jpg' %}" class="sd"><img src="{% static 'images/smp.jpg' %}" class="smp"> <img src="{% static 'images/sma.png' %}" class="sma"> <img src="{% static 'images/kuliah.png' %}" class="kuliah"></p>
	</div>
	</div>
	
	

</body>
</html>

homepage/templates/story3iii.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 	<link rel="stylesheet" type="text/css" href="{% static 'css/Story3.css' %}">

	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<title>Contact</title>
</head>
<body>
	<div>
		<nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3">
  			<a class="navbar-brand" href="#"><img src="{% static 'images/logotitus.jpg' %}" style="width: 100px;height: 40px;"></a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
    			<ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:profile' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:about' %}">About <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Contact <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:photo' %}">Photo <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:profile' %}">Forms <span class="sr-only">(current)</span></a>
              </li>
          </ul>
  			</div>
		</nav>
	</div>
	<div id="bgcontact">
		<div>
			<img src="{% static 'images/titus3.png' %}" class="img-fluid" id="fotocontact">
		</div>
		<div>
			<p><a href="https://web.facebook.com/tius.pamungkas"><img src="{% static 'images/facebook.png' %}" class="socialmedia" id="facebook"></a> - <a href="https://twitter.com/TiusDirgantoro"><img src="{% static 'images/twitter.png' %}" class="socialmedia"></a> - <a href="https://www.instagram.com/titus_dp/"><img src="{% static 'images/instagram.png' %}" class="socialmedia"></a></p>
		</div>
		
	</div>
</body>
</html>

homepage/templates/story3iv.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<title>Photo</title>
</head>
<body>
	<div>
		<nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3">
  			<a class="navbar-brand" href="#"><img src="{% static 'images/logotitus.jpg' %}" style="width: 100px;height: 40px;"></a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
    			<ul class="navbar-nav">
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:profile' %}">Home <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:about' %}">About <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:contact' %}">Contact <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:photo' %}">Photo <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:profile' %}">Forms <span class="sr-only">(current)</span></a>
      				</li>
    			</ul>
  			</div>
		</nav>
	</div>
	
	<div class="container"> 
		<div class="bd-example">
			<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
					<li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
					<li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
					<li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
				</ol>
				<div class="carousel-inner">
					<div class="carousel-item active">
						<img src="{% static 'images/aamabaui.jpg' %}" class="d-block w-100" alt="...">
						<div class="carousel-caption d-none d-md-block">
							<h5>Waktu OSPEK</h5>
							<p>@luarbalairung</p>
						</div>
					</div>
					<div class="carousel-item">
						<img src="{% static 'images/aaparade.jpeg' %}" class="d-block w-100" alt="...">
						<div class="carousel-caption d-none d-md-block">
							<h5>Parade CSUI</h5>
							<p>@sekitargedunglamaFasilkom</p>
						</div>
					</div>
					<div class="carousel-item">
						<img src="{% static 'images/aaruntime.jpg' %}" class="d-block w-100" alt="...">
						<div class="carousel-caption d-none d-md-block">
							<h5>Runtime Error</h5>
							<p>@ParBel</p>
						</div>
					</div>
					<div class="carousel-item">
						<img src="{% static 'images/aatitussma.jpg' %}" class="d-block w-100" alt="...">
						<div class="carousel-caption d-none d-md-block">
							<h5>kelas 12 sma</h5>
							<p>@sman4bekasi</p>
						</div>
					</div>
				</div>
				<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
 
	</div>
</body>
</html>

homepage/templates/story3v.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

	<title>Form Schedule</title>
</head>
<body>
	<div>
		<nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3">
  			<a class="navbar-brand" href="#"><img src="{% static 'images/logotitus.jpg' %}" style="width: 100px;height: 40px;"></a>
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
    			<ul class="navbar-nav">
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:profile' %}">Home <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:about' %}">About <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:contact' %}">Contact <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:photo' %}">Photo <span class="sr-only">(current)</span></a>
      				</li>
      				<li class="nav-item active">
        				<a class="nav-link" href="{% url 'homepage:kegiatan' %}">Forms <span class="sr-only">(current)</span></a>
      				</li>
    			</ul>
  			</div>
		</nav>
	</div>
    
    <form action="{% url 'homepage:tambah' %}" method="POST" role="form">
     	{% csrf_token %}    
        
            <label for = "name"style="color: #ededed";font-size:100px;>Nama Kegiatan</label> 
            {{form.name}} 
	  <div class="form-group">
	    <label  style="color: #ededed">Tempat</label>
	    <div class="input-group" style="background-color: white">{{form.tempat}}</div>
	  </div>
	  <div class="form-group">
	    <label style="color: #ededed">Tanggal</label>
	    <div class="input-group" style="background-color: white">{{form.tanggal}}</div>
	  </div>
	  <div class="form-group">
	    <label style="color: #ededed">Jam</label>
	    <div class="input-group" style="background-color: white">{{form.jam}}</div>

	  </div>
	  <div class="form-group">
	    <label style="color: #ededed">Kategori</label>
	    <div class="input-group" style="margin-left: 3vw;">{{form.kategori}}</div>
	</div>
	<div><span class="input-group-btn">
		<button type="submit" class="btn" id="add-btn" style="color: #ededed">ADD</button>
    </span></div>

	</div>
	</form>

	<ul class="list-group t20" style="margin-right: 40vw; margin-top: 3vw; font-size:1.111vw;">
                <table>
                    <tr>
                        <td>
                            <li class="list-group-item">Kegiatan</li>
                        </td>
                        <td>
                            <li class="list-group-item">Tanggal</li>
                        </td>
                        <td>
                            <li class="list-group-item">Tempat</li>
                        </td>
                        <td>
                            <li class="list-group-item">Jam</li>
                        </td>
                        <td>
                            <li class="list-group-item">Kategori</li>
                        </td>
                    </tr>
                </table>
                {% for kegiatan in list_schedule %}
                <table>
                    <tr>
                        <td>
                            <li class="list-group-item">{{ kegiatan.name }}</li>
                        </td>
                        <td>
                            <li class="list-group-item">{{ kegiatan.tanggal }}</li>
                        </td>
                        <td>
                            <li class="list-group-item">{{ kegiatan.tempat }}</li>
                        </td>
                        <td>
                            <li class="list-group-item">{{ kegiatan.jam }}</li>
                        </td>
                        <td>
                            <li class="list-group-item">{{ kegiatan.kategori }}</li>
                        </td>
                        <td>
                            {% if kegiatan.pilih %}
                            <a href="{% url 'homepage:pilih' kegiatan.id %}">
                                <button class="btn" style="color: #ededed"> x
                                </button>
                            </a>
                            {% else %}
                            <a href="{% url 'homepage:pilih' kegiatan.id %}">
                                <button class="btn" style="background-color: #ededed; color: #ededed"> x
                                </button>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                </table>
                {% endfor %}
                <a href="{% url 'homepage:hapus' %}" style="margin-top: 3vw;"><span class="input-group-btn">
                        <button type="button" class="btn" id="add-btn" style="color: red">Delete</button>
                    </span></a>
            </ul>
        </div>

</body>
</html>